// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DocusealController from "./docuseal_controller"
application.register("docuseal", DocusealController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import TiptapEditorController from "./tiptap_editor_controller"
application.register("tiptap-editor", TiptapEditorController)
