// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ContractEditorController from "./contract_editor_controller"
application.register("contract-editor", ContractEditorController)

import ContractViewerController from "./contract_viewer_controller"
application.register("contract-viewer", ContractViewerController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import TiptapController from "./tiptap_controller"
application.register("tiptap", TiptapController)
